server:
  port: 9001
spring:
  rabbitmq:
    addresses: 47.98.131.252
    host: 47.98.131.252
    port: 5672
    username: limingyang
    password: asd.1234
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual #手动签收
        retry:
          enabled: true   #开启重试机制
          max-attempts: 4 #重试最大次数
          max-interval: 10000 #重试最大时间间隔
          initial-interval: 1000 #重试初始时间间隔
          multiplier: 1 #间隔时间乘子 ，间隔时间*乘子=下一次的间隔时间，最大不能超过设置的最大间隔时间
  datasource:
    url: jdbc:mysql://172.20.4.187.3307/my_test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
